apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "sdchart.fullname" . }}-keda-trigger-auth-aws-credentials
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
spec:
  podIdentity:
    provider: aws-eks