apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ include "sdchart.fullname" . }}-provisioner-gpu
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
spec:
  {{- if .Values.karpenter.provisioner.labels }}
  labels:
  {{- toYaml .Values.karpenter.provisioner.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.karpenter.provisioner.consolidation }}
  consolidation:
    enabled: true
  {{- end }}
  {{- if .Values.karpenter.provisioner.resourceLimits }}
  limits:
    resources:
  {{- toYaml .Values.karpenter.provisioner.resourceLimits | nindent 6 }}
  {{- end }}
  providerRef:
    name: {{ include "sdchart.fullname" . }}-nodetemplate-gpu
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    {{- if .Values.karpenter.provisioner.capacityType.spot }}
    - spot
    {{- end }}
    {{- if .Values.karpenter.provisioner.capacityType.onDemand }}
    - on-demand
    {{- end }}
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    {{- toYaml .Values.karpenter.provisioner.instanceType | nindent 4 }}
  {{- if .Values.karpenter.provisioner.extraRequirements }}
  {{- toYaml .Values.karpenter.provisioner.extraRequirements | nindent 2 }}
  {{- end }}
  taints:
  - effect: NoSchedule
    key: nvidia.com/gpu
  - effect: NoSchedule
    key: runtime
    value: {{ include "sdchart.fullname" . }}
  {{- if .Values.karpenter.provisioner.extraTaints }}
  {{- toYaml .Values.karpenter.provisioner.extraTaints | nindent 2 }}
  {{- end }}